# Site
title: Polkadot Ecosystem Insights
subtitle: 'Exploring ASTR, PEAQ, and Beyond'
description: 'Deep dives into the Polkadot ecosystem, focusing on Astar Network and PEAQ'
keywords: polkadot, astar, peaq, blockchain, web3
author: Blockchain Enthusiast
language: en
timezone: ''

# URL
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
  Astar Network: astar
  PEAQ: peaq
  Polkadot: polkadot
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: jekyll-theme-minimal

# Deployment
deploy:
  type: ''
